############################# English ############################
[en]
languageName = "En"
title = "Bigspring Hugo"
contentDir = "content/english" # content/english
weight = 1
########### footer content ##########
footer_menu_left = "Importante"
footer_menu_middle = "Tutoriales"
footer_menu_right = "Administrativo"
footer_content = "Maestría en Desarrollo Regional"
# copyright
copyright = "José Luis Manzanares Rivera site Design By [Themefisher](https://themefisher.com/) Develop By [Gethugothemes](https://gethugothemes.com/)"



############################# Deutsch ############################

########### footer content ##########
footer_menu_left = "Firma"
footer_menu_middle = "Produkte"
footer_menu_right = "Support"
footer_content = "Lorem ipsum dolor sit amet, consectetur elit. Consjat tristique eget amet, tempus eu at cttur."
# copyright
copyright = "Design von [Themefisher](https://themefisher.com/) Entwickelt von [Gethugothemes](https://gethugothemes.com/)"